export const STARSHIPS_START_FETCHING = 'STARSHIPS_START_FETCHING';

export const STARSHIPS_STOP_FETCHING = 'STARSHIPS_STOP_FETCHING';

export const STARSHIPS_SET_FETCHING_ERROR = 'STARSHIPS_SET_FETCHING_ERROR';

export const STARSHIPS_FETCH_ASYNC = 'STARSHIPS_FETCH_ASYNC';

export const STARSHIPS_FILL = 'STARSHIPS_FILL';
